koor/config/common.py
superadmin/admin.py
superadmin/apps.py
superadmin/models.py
superadmin/tests.py
superadmin/views.py

Here we create a super admin module and install this app into the common config file.

#71 - create superadmin module

---

koor/urls/v1.py
superadmin/serializers.py
superadmin/urls.py
superadmin/views.py

Here we create CreateCountrySerializers and CountryView class for create country.
Set validation only admin can add country.
Serializer class for the `Country` model.
The `CreateCountrySerializers` class extends `serializers.ModelSerializer` and is used to create instances of the `Country` model. It defines the fields that should be included in the serialized representation of the model, including 'title', 'currency_code', 'country_code', 'iso_code2', and 'iso_code3'.
API View class for creating a new country.
The `CountryView` class extends the `generics.GenericAPIView` and is used to create a new country in the system.
The `post` method is overridden to handle the creation of the country. Theserializer class used for this view is `CreateCountrySerializers`. The view requires …

#65 - create country

---

core/models.py
core/pagination.py
koor/urls/v1.py
project_meta/models.py
superadmin/serializers.py
superadmin/urls.py
superadmin/views.py
users/views.py

Here we create CustomPagination in pagination file.
Here we modify CountryView class for get country data.
Set validation for all authenticated user.
Custom pagination class for handling pagination of query results.
- `page_size (int)`: The number of items to be displayed per page. Default is `10`.
- `page_size_query_param (str)`: The name of the query parameter used to specify the number of items to be displayed per page. Default is `"limit"`.
- `max_page_size (int)`: The maximum number of items that can be displayed per page. Default is `1000`.
A view for displaying a list of countries.
- `permission_classes ([permissions.IsAuthenticated])`: List of permission classes that the view requires. In this case, only authenticated users are allowed to access the view.
- `serializer_class …

#66 - getallcountry

---

core/models.py
core/pagination.py
project_meta/models.py
superadmin/serializers.py
superadmin/urls.py
superadmin/views.py
users/views.py

Here we create `CitySlugBaseModel`, `CitySerializers` and `CityView`.
- Change slug base model from `SlugBaseModel` to `CitySlugBaseModel` for auto generate slug value.
- Create url path for create and get City api
This abstract base model is used to store information in a Django Model.
- `title`: A string representing the name of the model.
- `slug`: A string representing the slug for the model, used in URLs and filtering record.
Serializer class for City model.
- This serializer class is based on Django Rest Framework's ModelSerializer and it is used to represent the City model in the API.
- The serializer defines the fields that should be included in the API representation using the fields attribute.
- The serializer also includes a validation method (validate) to validate the data …

#69 - create city

---

superadmin/serializers.py
superadmin/urls.py
superadmin/views.py

Here we create `JobCategorySerializers` and `JobCategoryView`.
- Create url path for create and get job category api
Serializer class for the `JobCategory` model.
The `JobCategorySerializers` class extends `serializers.ModelSerializer` and is used to create instances of the `JobCategory` model. It defines the fields that should be included in the serialized representation of the model, including 'id', 'title'.
A view for displaying a list of job categories.
- `permission_classes ([permissions.IsAuthenticated])`: List of permission classes that the view requires. In this case, only authenticated users are allowed to access the view.
- `serializer_class (JobCategorySerializers)`: The serializer class used for data validation and serialization.
- `queryset (QuerySet)`: The queryset that the …

#76 - create and get jobcategory

---

superadmin/serializers.py
superadmin/urls.py
superadmin/views.py

Here we create `EducationLevelSerializers` and `EducationLevelView`.
- Create url path for create and get education level api
Serializer class for the `EducationLevel` model.
The `EducationLevelSerializers` class extends `serializers.ModelSerializer` and is used to create instances of the `EducationLevel` model. It defines the fields that should be included in the serialized representation of the model, including 'id', 'title'.
A view for displaying a list of education levels .
- `permission_classes ([permissions.IsAuthenticated])`: List of permission classes that the view requires. In this case, only authenticated users are allowed to access the view.
- `serializer_class (EducationLevelSerializers)`: The serializer class used for data validation and serialization.
- `queryset …

#18 - create education level

---

koor/config/common.py

Modified the `CORS` header configuration.

#1 - Modified CORS Headers Configuration

---

core/middleware.py
users/serializers.py

- modify middleware status code if token is invalid.
- modify value of license_id_file in get user api.
- modify value of file_path in get user api.

#7 - get user details

---

core/middleware.py

Modify middleware for an access token:
If the access token is expired but the refresh token is valid so return a valid response.

#41 - modify middleware

---

superadmin/views.py

Remove pagination form response.

#66 - remove pagination

---

employers/views.py

- Modify jobs data filter and validation.
- If Authenticated is empoyer we send jobs data otherwise return blank array.

#41 - employer get jobs

---

employers/serializers.py

- added applicant and created in get job response.

#41 - add applicant and created

---

docs/job-seeker/job-seeker.md
job_seekers/serializers.py
job_seekers/urls.py
job_seekers/views.py
koor/urls/v1.py

Here we create `UpdateAboutSerializers` and `UpdateAboutView`.
- Create url path for create job seekers update about me api.
- Modify data format of dob for update about me in job seekers docs file.
A serializer for updating JobSeekerProfile instances, including the name of the associated User.
- `full_name`: A CharField for the full name of the `JobSeekerProfile`, used to update the associated `User's name`.
- `model`: The `JobSeekerProfile` model to be serialized.
- `fields`: The fields of the `JobSeekerProfile` to be included in the serializer.
- `update`: Update the `JobSeekerProfile` instance with the provided validated data, and update the `associated User's name` if the `full_name` field is included.
- The updated JobSeekerProfile instance.
A view for updating the JobSeekerProfile …

#21 - edit about me

---

jobs/admin.py

- Show `job details`, `job category` and `job attachments item` table in admin panel.

#41 - show table in admin panel

---

docs/user/user.md
jobs/admin.py
users/backends.py
users/serializers.py

- Add role paramete in create user session api.
- Before create session we check user role.
- Modify create session api doc
Add role parameter in request body for create session.

#5 - create session

---

docs/job-seeker/job-seeker.md
docs/user/user.md
job_seekers/urls.py
job_seekers/views.py

Here we create `JobSearchView`.
- Create url path for create job search api.
- Add Get Jobs Search for job search api in job seekers docs file.
API endpoint that lists all job details based on a search query.
The endpoint requires authentication to access and returns a paginated list of job details sorted by their creation date in descending order. The list can be filtered by job title.
- `serializer_class`: The serializer class used to serialize job details data.
- `permission_classes`: A list of permission classes that apply to the view.
- `queryset`: The queryset of job details used to retrieve data.
- `filter_backends`: A list of filter backend classes used to filter job details data.
- `search_fields`: A list of fields on which the search query can be performed.
- `pagination_class`: …

#92 - search jobs

---

employers/views.py

- Solve error if `JobSeeker` use `GetEmployerJobs` api.

#41 - Solve error when job seeker use employer job api

---

job_seekers/views.py

- Change permission of `GetJobSearch` API for `all user`.

#92 - change permission for all user

---

job_seekers/serializers.py
job_seekers/urls.py
job_seekers/views.py
koor/config/common.py

Here we create `GetJobsDetailSerializers` and `GetJobDetailsView`.
- Create URL path for creating job detail by id API.
- Modify the date and time format.

#93 - getjobdetailsbyid

---

core/pagination.py
docs/admin/admin.md
employers/views.py
koor/config/common.py

- Modify page size and max page size for custom pagination.

#41- modify page_size and max_page_size

---

core/middleware.py

Fixed the `middleware` to resolve `DecodeError`

#1 - Fix the Decode Error in middleware

---

users/serializers.py
users/urls.py
users/views.py

Here we create `UpdateImageSerializers` and `DisplayImageView` class.
- Create url for add update profile image.
Serializer class for `updating a user's profile image`.
- `profile_image (FileField)`: A file field that represents the user's new profile image.
Validates that the uploaded profile image is a valid image file.
- `profile_image (File)`: The profile image file to validate.
- `File`: The validated profile image file.
- `ValidationError`: If the profile image file is `blank or invalid`.
Updates the user's profile image.
- `instance (User)`: The User instance to update.
- `validated_data (dict)`: The validated data containing the new profile image.
- `User`: The updated `User` instance.
API view class for displaying and updating a user's profile image.
- `serializer_class …

#106 - update profile image

---

job_seekers/serializers.py

- Modify file response for get job details api.

#93 - update get job detail response

---

job_seekers/views.py

- Created delete function in `EducationView` for `delete` education for jobseekers.

#20 - create delete function

---

employers/views.py
job_seekers/serializers.py
job_seekers/urls.py
job_seekers/views.py

25 add language

---

employers/serializers.py

- Set the required language, skill, and job category for creating and updating jobs.

#42 - language skill and job category required

---

job_seekers/serializers.py
job_seekers/urls.py
job_seekers/views.py

- create add work experiences API.

#28 - add work experience

---

job_seekers/serializers.py
job_seekers/urls.py
job_seekers/views.py

- create update work experiences API.

#29 - update work experience

---

job_seekers/serializers.py
job_seekers/urls.py
job_seekers/views.py

- create delete work experiences API.

#30 - delete work experience

---

job_seekers/admin.py
job_seekers/serializers.py
job_seekers/urls.py
job_seekers/views.py

- show table `JobSeekerLanguageProficiency`, `EmploymentRecord`, `JobSeekerSkill` in admin panel.
- create `JobSeekerSkillSerializers` and `SkillsView` for add skill.
- create url path for add skill for job seekers.

#31 - add skill

---

docs/admin/admin.md
superadmin/urls.py
superadmin/views.py

- Create delete function for delete city.
- Create url for delete city.

#70 - delete city

---

docs/admin/admin.md
superadmin/urls.py
superadmin/views.py

- Create a delete function for delete city.
- Create URL for delete city.

#67 - deletecountry

---

superadmin/urls.py
superadmin/views.py

- Create a delete function for the delete skill.
- create URL for delete skill.

#17 - delete skills

---

superadmin/urls.py
superadmin/views.py

- Create a delete function for the delete Language.
- create a URL for deleting Language.

#14 - delete language

---

superadmin/serializers.py
superadmin/urls.py
superadmin/views.py

- Create a `TagView` and `TagSerializers` for create and get tags.
- create URL for create and get tags.

#9 - create tag

---

superadmin/serializers.py
superadmin/urls.py
superadmin/views.py

- Create a delete function for the delete Tag.
- create URL for delete Tag.

#11 - delete tags

---

docs/job-seeker/job-seeker.md
job_seekers/urls.py
job_seekers/views.py
users/serializers.py

- Create a `JobsUnsaveView` for unsave jobs from the saved job list.
- create URLs for unsave jobs.

#138 - features

---

docs/job-seeker/job-seeker.md
job_seekers/urls.py
job_seekers/views.py
users/serializers.py

- remove `present` field form `EmploymentRecord`

#7 - remove present form EmploymentRecord

---

docs/job/job.md
employers/admin.py
jobs/serializers.py
jobs/urls.py
jobs/views.py
users/serializers.py

- add `applicant` count in `job search api` and `job detail api`.

#41 - add applicent count in jobs api

---

users/urls.py
users/views.py

- modify create `change password` api's function.
- create url for `change password` api.

#6 - forget password

---

superadmin/views.py
users/serializers.py

- add the `description` parameter in the `UserSerializers` serializers response.

#138 - add description in user serializer

---

job_seekers/serializers.py
jobs/serializers.py
jobs/views.py

- create `GetAppliedJobsSerializers` in the jobs app.
- call `GetAppliedJobsSerializers` from the jobs app for `ApplicationsDetailView`.
- modify the response of `GetAppliedJobsSerializers`.

138 features

---

jobs/serializers.py

- create `AppliedJobAttachmentsSerializer` in the jobs app.

#138 - create AppliedJobAttachmentsSerializer

---

job_seekers/serializers.py

- remove duplicate `AppliedJobAttachmentsSerializer` in the jobs seeker app.

#138 - remove duplicate AppliedJobAttachmentsSerializer

---

docs/admin/admin.md

- modify `admin.md` for admin API Doc.

#138 - modify admin doc

---

superadmin/admin.py
superadmin/models.py
superadmin/serializers.py
superadmin/views.py

- set `title` as the default return value for the `Content` table.
- show the `Content` table in the admin panel.
- create an update function in `ContentSerializers` for the update description.
- create a patch function in `UserRightsView` for updating user rights.
Handle PATCH requests to update a Content object.
- `request (Request)`: The incoming PATCH request.
- A Response object with a success message if the user is a staff member and the update was successful, or an error message, if the user does not have permission to perform the action or the data provided in the request, is invalid.
- N/A
- This function first checks whether the user making the request is a staff member.
- If so, it looks for an existing Content object with the title "User Rights".
- If one exists, it updates …

#167 - update user rights

---

superadmin/views.py

- create a patch function in `PrivacyPolicyView` for updating user rights.
Handle PATCH requests to update a Content object.
- `request (Request)`: The incoming PATCH request.
- A Response object with a success message if the user is a staff member and the update was successful, or an error message, if the user does not have permission to perform the action or the data provided in the request, is invalid.
- N/A
- This function first checks whether the user making the request is a staff member.
- If so, it looks for an existing Content object with the title "User Rights".
- If one exists, it updates that object with the data provided in the request.
- If not, it either finds a previously removed object with that title and un-removes it or creates a new object with that title.
- It then …

#169 - create patch function in PrivacyPolicyView

---

docs/admin/admin.md

- modify `admin.md` for admin API doc format.

#169 - modify admin.md

---

docs/admin/admin.md
jobs/views.py
superadmin/serializers.py
superadmin/urls.py
superadmin/views.py

- Create a URL path to get the count for the dashboard API.
- Created `UserCountSerializers` and `UsersCountView` to get the count for dashboard API.
A serializer that converts user count data to/from JSON format.
- `total_user (int)`: The total number of registered users in the system.
- `job_seekers (int)`: The number of registered users with the 'job_seeker' role.
- `employers (int)`: The number of registered users with the 'employer' role.
- `vendors (int)`: The number of registered users with the 'vendor' role.
- `active_user (int)`: The number of users who are currently logged in to the system.
- `total_jobs (int)`: The total number of jobs posted in the system.
- `active_jobs (int)`: The number of jobs that are currently active and open for applications.
- `get_active_jobs(self, …

#159 - get users count

---

superadmin/urls.py
superadmin/views.py

- Create a URL path for deleting jobs API.
- Created a `delete function` for delete jobs.
Deletes a Job object with the given ID if the authenticated user is an admin.
- `request`: A DRF request object.
- `jobId`: An integer representing the ID of the Job to be deleted.
A DRF response object with a success or error message and appropriate status code.

#184 - delete jobs

---

superadmin/urls.py
superadmin/views.py

- Created a `patch function` for modifying jobs status.
View function for `updating the status` of a job instance.
- `request`: Request object containing metadata about the current request.
- `jobId`: Integer representing the ID of the job instance to be updated.
Response object containing data about the updated job instance, along with an HTTP status code.
- `Http404`: If the job instance with the given `jobId does not exist`.

#185 - inactive jobs

---

docs/admin/admin.md
superadmin/urls.py
superadmin/views.py

- Create a URL path for deleting employer API.
- Created a `delete function` for deleting employer API.
Deletes a User object with the given ID if the authenticated user is an admin.
- `request`: A DRF request object.
- `employerId`: An integer representing the ID of the User to be deleted.
A DRF response object with a success or error message and appropriate status code.

#186 - delete employers

---

docs/admin/admin.md
superadmin/urls.py
superadmin/views.py

- Created a `patch function` for active or inactive users.
View function for `updating the status` of a user instance.
- `request`: Request object containing metadata about the current request.
- `userId`: Integer representing the ID of the user instance to be updated.
Response object containing data about the updated user instance, along with an HTTP status code.
- `Http404`: If the user instance with the given `userId does not exist`.

#187 - inactive users

---

core/tokens.py
requirements.txt
users/urls.py
users/views.py

- Created `requests==2.28.2` package name in `requirements.txt`.

#200 - add requests==2.28.2 package name

---

employers/views.py

#41 - modify context value

---

jobs/serializers.py
jobs/views.py

- Modify context value.
- Check context value in serializers file.

#203 - verified email api

---

users/views.py

- account verified when using social login.

#200 - account verified for social login

---

users/views.py

- account `verified` for creating user API.

#4 - set account verified

---

users/serializers.py
users/views.py

- display image when the user uses social login API.

#200 - save display image

---

jobs/views.py

- remove duplicate data from the response.

#92 - remove duplicate data

---

job_seekers/views.py

- set ordering for `apply job api` and `save job api`.

#217 - set ordering for saved and applied job

---

jobs/urls.py
jobs/views.py

- create a `delete function` in `JobFilterView` to remove the search filter.
- create a URL path to remove the search filter.
A function to delete a job filter instance for a job seeker user.
- `request (HttpRequest)`: An HTTP request object.
- `filterId (int)`: An integer representing the ID of the job filter instance to be deleted.
- A Response object with a JSON representation of a message indicating the result of the operation and the HTTP status code.
- `JobFilters.DoesNotExist`: If the job filter instance with the given filterId and user does not exist.
- `Exception`: If there is any other error during the deletion process.

#217 - get saved filter

---

core/middleware.py

- send token if email is not verified.

#4 - modify middleware

---

core/middleware.py

Reverts digimonkt/koor-backend#211

Revert "#4 - modify middleware"

---

jobs/serializers.py
jobs/views.py

- Get job detail without login.

#93 - get response without login

---

job_seekers/serializers.py

- Modify the `is_saved` value in the saved job API response.

#217 - modify is_saved value in saved job

---

jobs/views.py

- Remove duplicate data form the `Get Job Suggestion` API.

#92 - remove duplicate data in suggestion

---

jobs/serializers.py

- Get suggested data without `login`.

#92 - get suggest job without login

---

jobs/urls.py
jobs/views.py

- Modify the method for updating application status.

#229 - create notification

---

notification/serializers.py

- add `job creator` data into get notification `response` data.

#231 -job creator data in response

---

superadmin/views.py

- Remove authentication permission for all get apis.

#66 - remove authenticated user permission

---

job_seekers/serializers.py
job_seekers/urls.py
job_seekers/views.py
koor/config/common.py
notification/serializers.py

- Modify response of getting notification API.
- create a URL path for updating job preferences.
- create `GetAppliedJobsNotificationSerializers`, `UpdateJobPreferencesView`, and `UpdateJobPreferencesSerializers` for update job preferences.
Serializer for the 'AppliedJob' model, used for generating notification data.
This serializer is used to generate notification data for job applicants.
It includes fields for the ID, shortlisted/rejected timestamps, cover letter, job object, user object, and attachments associated with an applied job.
- `id (int)`: The ID of the applied job.
- `shortlisted_at (datetime)`: The timestamp of when the job was shortlisted.
- `rejected_at (datetime)`: The timestamp of when the job was rejected.
- `short_letter (str)`: The cover letter provided by the …

#245 - update job preferences

---

job_seekers/serializers.py
job_seekers/urls.py
job_seekers/views.py
koor/config/common.py
notification/serializers.py
superadmin/serializers.py
superadmin/views.py

- add pagination in job list API for admin.
- add company for job list API.

#162 - get jobs list

---

job_seekers/serializers.py
job_seekers/urls.py
job_seekers/views.py
koor/config/common.py
notification/serializers.py
superadmin/serializers.py
superadmin/views.py

- add pagination in employer list API for admin.

#164 - get employers list

---

job_seekers/serializers.py
job_seekers/urls.py
job_seekers/views.py
koor/config/common.py
notification/serializers.py
superadmin/serializers.py
superadmin/views.py

- add pagination in candidates list API for admin.

#165 - get candidates list

---

users/views.py

- create `Put Function` in `UserFilterView` for updating the user's advanced filter.
A function to partially update a user filter instance for a user.
- `request (HttpRequest)`: An HTTP request object.
- `filterId (int)`: An integer representing the ID of the user filter instance to be updated.
- A Response object with a JSON representation of a message indicating the result of the operation and the HTTP status code.
- `UserFilters.DoesNotExist`: If the user filter instance with the given filterId and user does not exist.
- `Exception`: If there is any other error during the partial update process.

#264 - put function for update filter

---

superadmin/views.py

- set `search filter` in the job, employer, and candidate list

#162 - set filter in job, employer and candidate list

---

employers/serializers.py
employers/urls.py
employers/views.py

- create a URL path for updating tenders API.
- create `UpdateTenderSerializers` and `PUT function` in `TendersView` for update tenders API.
A serializer that handles the validation and updating of tender details for a PUT request.
- `serializers.ModelSerializer`: Inherits from the Django REST Framework's ModelSerializer.
- Defines various fields as PrimaryKeyRelatedField and ListField for the tender category, tags, and attachments of a tender. Validates these fields with custom validation methods.
- Defines a Meta class to specify the model and fields to be used in the serializer.
- Validates the tender category and tags fields and raises validation errors if necessary. Also ensures that these fields are not empty.
- Overrides the update() method to allow updating of tender details, …

#284 - update tenders

---

job_seekers/views.py
koor/config/common.py

- create function `RemoveAvailability` for removing availability every week.
- create cron time for `RemoveAvailability`.

#311 - remove availability every week

---

docs/user/user.md

- modify API doc for user's API in user.md file.

#314 - modify api doc for user

---

docs/user/user.md
jobs/views.py

- add paramter for count in response like: `rejected_count`, `shortlisted_count`, `planned_interview_count`, `blacklisted_count`.
- remove duplicate data in get job suggestion api

#316 - job application filter

---

jobs/views.py

- remove duplicate data in get job suggestion api

#316 - remove duplicate data

---

jobs/views.py

- show only active jobs in job search API.

show only active job

---

docs/admin/admin.md
superadmin/serializers.py
superadmin/urls.py
superadmin/views.py

- modify API doc for admin's API in the `admin.md` file.
- add delete URL path.
- add pagination for all get API.
- add validation for duplicate titles.

#314 - modify api doc

---

job_seekers/serializers.py
notification/serializers.py

- add the user's email address in getting notifications API's response.

#231 - add user email in response

---

docs/employer/employer.md
docs/job/job.md
employers/serializers.py
jobs/serializers.py

- modify API doc according to new changes.
- show experience in API response.

#40 - employer create jobs

---

docs/employer/employer.md
employers/serializers.py
employers/urls.py
employers/views.py

- modify employer.md for Dashboard Job Analysis.
- create a URL path for job analysis API.
- create function `JobAnalysisView` for job analysis in employer dashboard API.
A view that returns month-wise count of job details created by employers.
- `IsAuthenticated`: User must be authenticated.
- `GET`: Get the count of job details created by employers per month.
- `200 OK`: Returns a JSON object with the `month-wise count` of job details.
- `400 BAD REQUEST`: Returns a JSON object with an error message if an exception occurs.
- `401 UNAUTHORIZED`: Returns a JSON object with an error message if the user is not an employer.
Get the count of job details created by employers per month.
- If the user is an employer, returns a JSON object with the month-wise count of job details.
- If the user …

#332 - job analysis

---

job_seekers/urls.py
job_seekers/views.py
requirements.txt

- modify requirements.txt and add the `python-docx` package.
- create a URL path for creating docx file for a resume.
- create the function `ResumeView` to create docx file for a resume.
View for generating a resume in Microsoft Word format (.docx).
The view supports only authenticated users with a role of 'job_seeker'.
The generated resume includes the user's name, contact information, profile summary, skills, education, employment summary, and language proficiency.
The generated file is saved to the media folder and the response includes the URL to download the file.
- This view uses the `python-docx` library for generating the Word document.
- ModifyCategoriesSerializers
- IsAuthenticated
- get -- Generates a resume based on the logged-in user's information.
- A JSON response …

#334 - create doc file for resume

---

notification/serializers.py

- modify the `image` parameter to get notification API and solve errors.

#231 - modify image parameter for response

---

users/serializers.py

- set condition for user description.

#338 - set condition for user description

---

jobs/views.py

- get job applications with a `blacklisted` filter.

#316 - job application blacklist filter

---

job_seekers/views.py

- add validation for the `revoke applied job` API.

#194 - set validation for revoke applied job

---

job_seekers/views.py
superadmin/views.py
users/serializers.py

- modify `JobsListView` for downloading the `.csv` file for the job list.
- create `create_directory` to create a directory for storing the `job.csv` file.
- set try except function for user search API.

#345 - download csv file for job employer candidate and vendor

---

jobs/serializers.py

- remove the array from `job_category` and `job_sub_category` in the job detail response.

#367 - remove array in job detail response

---

docs/job/job.md
jobs/views.py

- modify option form `interview_planned` to `planned_interviews`.

#367 - change option from interview_planned to planned_interviews

---

jobs/serializers.py

- add `is_editable` in the get job detail response.

#374 - add is_editable in job detail response

---

superadmin/serializers.py
superadmin/urls.py
superadmin/views.py

- create `AllCitySerializers` and `WorldCityView` to get world cities data according to country.
- create a URL path for getting world cities data.
Serializer for AllCity model that returns a serialized representation of each city, including its country information. The 'country' field is a custom serializer method that returns the country information as a dictionary with 'id' and 'title' keys.
- `country`: A custom `SerializerMethodField` that returns the serialized representation of the country foreign key field of the AllCity model.
- `model`: AllCity model for which the serializer is defined.
- `fields`: A list of fields to be included in the serialized representation of the AllCity model. It includes 'id', 'title', and 'country' fields.
API view for retrieving a list of cities from …

#380 - update job seekers category

---

tenders/serializers.py

- add a deadline for getting the tenders API's response.

#281 - add deadline

---

users/views.py

- modify the talent search filter for display in the search function.

#247 - add filter for display user

---

superadmin/views.py

- modify get world city API now we get world city according to the country name.

#378 - modify get world city

---

users/views.py

- add `job category` and `job sub category` for talent search.

#247 - add jobCategory and jobSubCategory for telent search

---

users/serializers.py

- get many values in `organization_type` but send only one in response for getting user detail API. 

#404 - get many value for organization type

---

superadmin/urls.py
superadmin/views.py

- modify url name form `choice` to `sector` for get value for the enum. 

#404 - modify url form choise to sector

---

tenders/serializers.py

- modify sector value for tender response. 

#404 - modify sector value

---

employers/views.py
tenders/views.py

- modify the search field of sector value for tender search. 

#404 - create dynamic choice

---

users/serializers.py

- add sub-category for filter.

#404 - add sub category for filter

---

users/serializers.py

- add a subcategory to get the filter for talent search.

#404 - add subcategory for get filter data

---

job_seekers/views.py
jobs/views.py
vendors/views.py

- add a condition for order_by for the sort-by function.

#404 - add condition for order_by

---

employers/serializers.py

- update `start_date` and `deadline` for update tenders detail API.

#404 - update start_date and deadline

---

tenders/serializers.py

- modify response data for the `tag` field in the get saved advanced filter.

#404 - modify tag data response

---

tenders/filters.py
tenders/views.py

- modify filter for `opportunityType` in tender search.

#404 - modify filter for opportunityType

---

superadmin/serializers.py
superadmin/urls.py
superadmin/views.py

- create `TenderListSerializers`, `TenderListView`, and `TenderRevertView` for get, download, delete, revert, and active/inactive tender from admin.
- create URL path for `get`, `download`, `delete`, `revert`, and `active/inactive` tender from admin.

#423 - get tender list

---

employers/views.py
jobs/views.py

- add `search` parameter for `blacklisted` user and `recent job application`.

#423 - add search for recent application and blacklisted

---

employers/urls.py
employers/views.py

- get active jobs for any particular employer.

#423 - get employer active jobs

---

users/serializers.py

- modify get user detail api for vendor data.

#270 - update vendor profile for get user

---

users/views.py

- create vendor profile when vendor login with social login.

#270 - create vendor profile for social login

---

superadmin/serializers.py
superadmin/views.py

- send city id when the admin creates a new city.

#69 - send id in response

---

superadmin/serializers.py
superadmin/views.py

- update tender category function for admin.

#163 - update tender category api

---

tenders/urls.py
tenders/views.py

- create `TenderSuggestionView` to get tender suggestion API.
- create a URL path to get tender suggestion API.
API view for suggesting tenders based on matching criteria.
This view provides a list of suggested tenders based on matching criteria, including the budget amount, tags, tender category, tender type, and sector.
- serializer_class (class): The serializer class for the TenderDetails model.
- permission_classes (list): A list of permission classes to determine access to the view.
- query set (QuerySet): The initial query set for retrieving TenderDetails objects.
- filter_backends (list): A list of filter backends to apply for filtering the query set.
- filterset_class (class): The filter class for filtering the query set.
- search_fields (list): A list of fields to search for …

#442 - get suggestion tenders

---

superadmin/views.py

- modify create country API:- add id when making deleted country again.

#65 - add id when create country

---

superadmin/views.py

- hide job category if job subcategory is not available.

#76 - hide category if subcategory not available

---

tenders/serializers.py
tenders/views.py

- modify tender detail API like:- vendor applied or not, vendor count
- add the `is_editable` field in the tender detail serializer.

#292 - get tenders detail

---

tenders/serializers.py

- add the `application` field in the tender detail serializer.

#292 - add application field

---

tenders/urls.py
tenders/views.py
vendors/serializers.py

- modify `GetAppliedTenderSerializers` to remove extra tender detail.
- create `ApplicationsDetailView` to get tender application detail data.
- create a URL to get tender application detail data.

#459 - get tender application detail

---

vendors/serializers.py

- solve errors from remove attachments. 

#160 - solve error form remove attachments

---

tenders/serializers.py
tenders/urls.py
tenders/views.py

- create `AppliedTenderSerializers` and `TenderApplicationsView` to get tender application data for the employer.
- create a URL to get tender application data for employers.

#463 - tender applications

---

users/views.py

- create validation for the social login function.

#200 - validation for social login

---

tenders/urls.py
tenders/views.py

- create `RecentApplicationsView` for getting the recent tender application.
- create a URL path for getting the recent tender application.

#468 - get recent tender application

---

tenders/views.py

- import datetime for adding current DateTime.

#459 - call datetime

---

tenders/views.py

- remove the error when trying to send an email.

#459 - remove error for mail sending

---

superadmin/urls.py
superadmin/views.py

- create `ResourcesDetailView` for getting resources detail according to Id.
- create a URL for getting resources detail according to Id.

#477 - add update delete tags for vendor

---

jobs/views.py

- modify the `job sub category` filter in the job search API.

#92 - modify filter for job sub category

---

jobs/views.py

- modify JobCategoryView to get jobs and talents data for the footer.

#485 - modify JobCategoryView

---

jobs/views.py

- modify doc string for JobCategoryView.

#485 - modify doc string

---

jobs/urls.py
jobs/views.py

- create a URL to get popular job categories for the slider.
- create a `PopularJobCategoryView` function to get popular job categories for the slider.

#492 - popular categories for slider

---

jobs/views.py

- add id parameter in top categories API.

#492 - add id for top categories

---

employers/views.py
job_seekers/serializers.py
jobs/views.py
notification/views.py
tenders/views.py
vendors/serializers.py

- add validation for getting notifications and getting mail according to the user.

#497 - notification setting

---

superadmin/serializers.py

- add id in create top category log.

#513 - send id in response

---

superadmin/admin.py
superadmin/serializers.py
superadmin/views.py

- modify validation for faq category title. 

#160 - faq

---

superadmin/views.py

- create API for downloading job, candidate, employer, tender, closed job and closed tender, etc for reports. 

#160 - create download for reports

---

superadmin/views.py

- point credit into employer profile using recharge action by admin.

#523 - point credit into employer profile

---

superadmin/views.py

- change filter for download list.

#523 - change filter for download list

---

employers/views.py
superadmin/views.py

- modify the date time in the CSV file.
- send remaining_points in create job API's response

#523 - credit points

---

superadmin/serializers.py

- send points in the employer list api's response

#523 - send points in employer list api

---

superadmin/views.py

- add search fields in faq and faq category api.

#444 - add serach fields

---

employers/serializers.py
employers/views.py
vendors/views.py

- modify mobile number validation.

#444 - modify mobile number validation for update profile

---

users/serializers.py

- Get sector tag and organization type value in user filter data.

#444 - get sector tag and organization type value in user filter

---

superadmin/serializers.py
superadmin/views.py

- remove validation form update faq.

#444 - remove validation

---

superadmin/views.py

- modify employer list order for admin.

#444 - modify order for employer list

---

users/serializers.py

- add the `pay_period` parameter to get user detail API.

#245 - add pay_period for user detail

---

users/views.py

- add authentication to get user analytic API.

#245 - add authentication for user analytic

---

chat/views.py

- add a search function for conversation list.

#245 - add search for conversation list

---

chat/views.py

- add search for conversation list.

#245 - search conversation list api

---

project_meta/templates/email-templates/pdf-invoice.html
superadmin/process.py
superadmin/serializers.py
superadmin/urls.py
superadmin/views.py

- add `is_send` in invoice serializer data response.
- create html file to generate a pdf file.
- create process file for generating pdf file.
- create `InvoiceSendView` and `DownloadInvoiceView` to send invoices and generate pdf files for invoices.
- create a URL path for sending invoice API.

#590 - generate invoice

---

superadmin/urls.py
superadmin/views.py

- modify the `get invoice` API according to the frontend developer.

#590 - modify get invoice api

---

superadmin/serializers.py
superadmin/views.py

- add custom invoice id in all api for invoices.

#590 - add custom invoice id in all api

---

superadmin/serializers.py

- add user data in the `get invoice` and `get invoice detail` API.

#590 - add user detail in invoice api

---

superadmin/urls.py
superadmin/views.py

- Create Get more resources content according to ID.

#619 - get more resources api

---

job_seekers/views.py
tenders/views.py

- remove save job applicaion when apply by mail

#619 - more suggested resources

---

koor/config/common.py
project_meta/templates/email-templates/new/admin-verify-employer-account.html
project_meta/templates/email-templates/new/employer-registration.html
superadmin/views.py
users/serializers.py
users/views.py

send email to admin when new employe registered and send email to employe if admin verify account

#619 more suggested resources

---

koor/config/common.py
project_meta/templates/email-templates/pdf-invoice.html

In this i make conditional change 
where if the phone number is availabe than we have to show on the pdf invoice other vise that particular field will not show on user end

invoice Pdf

---

users/views.py

added the condition for create user without email

without email user creation
